<a href="https://colab.research.google.com/github/PaSathees/my-ai-courses/blob/main/3.%20UDEMY-PYTORCH/0.%20PyTorch%20Fundamentals/PyTorch%20Practice%2001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.0.1+cu118'

In [2]:
# Scaler
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor((7, 7))
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 6],
                        [2, 4, 6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 6],
         [2, 4, 6]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
# Create random tensor
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2257, 0.1353, 0.3482, 0.8730],
         [0.5269, 0.1858, 0.5625, 0.1138],
         [0.5556, 0.5583, 0.5455, 0.1779]]),
 torch.float32)

In [17]:
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
# Create all zeros tensor
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [19]:
# Create all ones tensor
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [20]:
# Use torch.arange()
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Creat like tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [23]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_16_tensor.dtype

torch.float16

In [24]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [25]:
tensor * 10

tensor([10, 20, 30])

In [26]:
tensor

tensor([1, 2, 3])

In [30]:
tensor = tensor - 10
tensor

tensor([-19, -18, -17])

In [32]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [33]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [34]:
tensor

tensor([1, 2, 3])

In [35]:
tensor * tensor

tensor([1, 4, 9])

In [36]:
# Matrix Multiplication
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [37]:
tensor * tensor

tensor([1, 4, 9])

In [38]:
torch.matmul(tensor, tensor)

tensor(14)

In [39]:
tensor @ tensor

tensor(14)

In [40]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 418 µs, sys: 0 ns, total: 418 µs
Wall time: 426 µs


tensor(14)

In [41]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.14 ms, sys: 8 µs, total: 1.15 ms
Wall time: 4.5 ms


tensor(14)

In [42]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [43]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [44]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
linear(tensor_A)

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

In [46]:
x= torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
x.min()

tensor(0)

In [48]:
x.max()

tensor(90)

In [49]:
x.type(torch.float32).mean()

tensor(45.)

In [50]:
x.sum()

tensor(450)

In [52]:
x.argmax()

tensor(9)

In [53]:
x.argmin()

tensor(0)

In [54]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [56]:
tensor_16 = tensor.type(torch.float16)
tensor_16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [57]:
tensor_8 = tensor.type(torch.int8)
tensor_8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [58]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [59]:
x.reshape(1, 7).shape

torch.Size([1, 7])

In [60]:
x.view(1, 7).shape

torch.Size([1, 7])

In [61]:
torch.stack([x, x, x, x], dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [62]:
torch.stack([x, x, x, x], dim=1)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [63]:
x.shape

torch.Size([7])

In [67]:
x.unsqueeze(dim=0).shape

torch.Size([1, 7])

In [68]:
x.unsqueeze(dim=1).shape

torch.Size([7, 1])

In [69]:
x.unsqueeze(dim=0).squeeze().shape

torch.Size([7])

In [71]:
c = torch.rand(size=(224, 224, 3))
c.permute(2, 0, 1).shape

torch.Size([3, 224, 224])

In [72]:
# indexing
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [73]:
x[:, 0]

tensor([[1, 2, 3]])

In [74]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [75]:
x[:, 1, 1]

tensor([5])

In [76]:
x[0, 0, :]

tensor([1, 2, 3])

In [78]:
# PyTorch & Numpy
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [79]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [80]:
tensor, tensor.numpy()

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [83]:
torch.manual_seed(seed=42)
torch.rand(3, 4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [1]:
!nvidia-smi

Mon Jul  3 15:24:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
torch.cuda.is_available()

True

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
torch.cuda.device_count()

1

In [6]:
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [7]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [8]:
tensor_gpu.numpy()

TypeError: ignored

In [9]:
tensor_gpu.cpu().numpy()

array([1, 2, 3])