<a href="https://colab.research.google.com/github/PaSathees/pytorch-course-1/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello! I am excited to learn PyTorch")

Hello! I am excited to learn PyTorch


In [2]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu117


## Introduction to Tensors

### Creating Tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0][0][1]

tensor(2)

### Random Tensors

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3 , 4)
random_tensor

tensor([[0.7886, 0.5809, 0.3172, 0.2200],
        [0.7279, 0.6988, 0.0458, 0.2644],
        [0.2597, 0.6508, 0.3359, 0.4062]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # heigth, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [24]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [29]:
# Use torch.range() -> deprecated
one_to_ten = torch.arange(1, 10)
one_to_ten 

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten 

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Usual errors in Pytorch
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # what datatype is the tensor (float32 or float 16)
                               device=None, # cpu or cuda
                               requires_grad=False) # track gradients
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [38]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4531, 0.4811, 0.7367, 0.3060],
        [0.9890, 0.8429, 0.5106, 0.5973],
        [0.4231, 0.3659, 0.8052, 0.0255]])

In [39]:
# find tensor attributes
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") #.size() is a function
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4531, 0.4811, 0.7367, 0.3060],
        [0.9890, 0.8429, 0.5106, 0.5973],
        [0.4231, 0.3659, 0.8052, 0.0255]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)
Tensor operation include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [40]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
 # Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [45]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

In [46]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [47]:
# Matrix multiplication
torch.matmul(tensor, tensor) # can use @ symbol too

tensor(14)

In [48]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3.25 ms, sys: 0 ns, total: 3.25 ms
Wall time: 6.47 ms


In [49]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 580 µs, sys: 0 ns, total: 580 µs
Wall time: 448 µs


tensor(14)

Two rules for matrix multiplication
1. The **inner dimensions** must match:
2. The resulting matrix has the shape of the **outer dimensions**

### One of the most common errors in deeplearning: shape errors

In [50]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [51]:
torch.mm(tensor_A, tensor_B.T) # Transpose

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [52]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

## Finding the min, max, mean, sum, etc (Tensor aggregations)

In [53]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
# Find the min
torch.min(x), x.min() 

(tensor(0), tensor(0))

In [55]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [56]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [57]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [58]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
# Find the position in tensor that has the minimum value
x.argmin()

tensor(0)

In [60]:
# Find the position in tensor that has the maximum value
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - to a defined shape
* View - gives defined shape but keeps original in memory
* Stacking - vstack or hstack
* Squeeze - removes 1 dimension
* Unsqueeze - adds 1 dimension
* Permute - return permuted view (swapped)

In [61]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [62]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [63]:
# Change the view
z = x.view(1, 9)
z, z.shape 

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [64]:
# changing view changes original one (same memory)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [65]:
# stack tenors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [66]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [68]:
# unsqueeze add 1 dim to specific dim
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [69]:
# permute rearranges the dimensions and gives a view
x_original = torch.rand(size=(224, 224, 3))

# permute the original
x_permuted = x_original.permute(2, 0, 1)

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [70]:
x_original[0, 0, 0] = 787890
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(787890.), tensor(787890.))

## Indexing (similar to Numpy)

In [71]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
# middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [74]:
# last bracket (dim=2)
x[0][2][2]

tensor(9)

In [75]:
# : all of the target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [76]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [77]:
x[:, 1, 1]

tensor([5])

In [78]:
x[0, 0, :]

tensor([1, 2, 3])

In [79]:
x[0, 2, 2]

tensor(9)

In [80]:
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors & Numpy
* Numpy to PyTorch -> `torch.from_numpy(ndarray)`
* PyTorch to Numpy -> `torch.Tensor.numpy()`

In [81]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
torch.arange(1.0, 8.0).dtype # different dtype

torch.float32

In [83]:
# tensor will not sync with numpy array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [84]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [85]:
tensor = tensor + 1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## Reproducibility (taking random out of random)
-> Random seed -> flavour randomnes

In [86]:
torch.rand(3, 3)

tensor([[0.7571, 0.0618, 0.4072],
        [0.7846, 0.9050, 0.4187],
        [0.5897, 0.5567, 0.8301]])

In [88]:
import torch

random_tensor_1 = torch.rand(3, 4)
random_tensor_2 = torch.rand(3, 4)

print(random_tensor_1, '\n', random_tensor_2)
print(random_tensor_1 == random_tensor_2)

tensor([[0.9217, 0.2279, 0.9493, 0.5818],
        [0.7865, 0.0959, 0.6966, 0.9317],
        [0.6920, 0.7096, 0.5175, 0.2874]]) 
 tensor([[7.1106e-01, 2.7275e-01, 6.2511e-01, 4.7160e-01],
        [4.2719e-04, 8.7254e-01, 3.7316e-01, 6.4197e-01],
        [1.2880e-01, 5.0880e-01, 7.0805e-01, 8.1028e-01]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [89]:
# random but reproducible
import torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) # should flavour every time creating tensors
random_tensor_1 = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_2 = torch.rand(3, 4)

print(random_tensor_1, '\n', random_tensor_2)
print(random_tensor_1 == random_tensor_2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running on GPU

### 1. Getting a GPU
1. Google Colab
2. Own GPU
3. Cloud computing - GCP, AWS, Azure

In [90]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


### Check GPU access with PyTorch

In [91]:
import torch
torch.cuda.is_available()

False

In [92]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [93]:
# count number of devices
torch.cuda.device_count()

0

### Putting tensors (and models) on the GPU

In [94]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [95]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors to CPU

In [96]:
# can't use GPU tensor with numpy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [97]:
# put back on the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [98]:
tensor_on_gpu

tensor([1, 2, 3])